cicd workflow develop

diff --git a/.github/workflows/deploy-image-gallery.yaml b/.github/workflows/deploy-image-gallery.yaml
--- a/.github/workflows/deploy-image-gallery.yaml
+++ b/.github/workflows/deploy-image-gallery.yaml
@@ -67,7 +67,7 @@ jobs:
       - name: Clean terraform directory
         run: rm -r /tmp/terraform
       - name: Fail pipeline
-      if: steps.apply.outcome != 'success'
-      run: |
-        echo "Terraform apply failed. Please, review logs"
-        exit 1
+        if: steps.apply.outcome != 'success'
+        run: |
+          echo "Terraform apply failed. Please, review logs"
+          exit 1
