cicd workflow develop

diff --git a/.github/workflows/deploy-scaleset.yaml b/.github/workflows/deploy-scaleset.yaml
--- a/.github/workflows/deploy-scaleset.yaml
+++ b/.github/workflows/deploy-scaleset.yaml
@@ -66,3 +66,8 @@ jobs:
       continue-on-error: true
     - name: Clean terraform directory
       run: rm -r /tmp/terraform
+    - name: Fail pipeline
+      if: steps.apply.outcome != 'success'
+      run: |
+        echo "Terraform apply failed. Please, review logs"
+        exit 1
